# Generated by Django 3.1.3 on 2021-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreJsonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('born', models.TextField(blank=True, null=True)),
                ('height', models.TextField(blank=True, null=True)),
                ('books', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('children', models.TextField(blank=True, null=True)),
                ('known_attributes', models.TextField(blank=True, null=True)),
                ('profiles', models.TextField(blank=True, null=True)),
                ('people_also_search_for', models.TextField(blank=True, null=True)),
                ('related_searches', models.TextField(blank=True, null=True)),
                ('related_questions', models.TextField(blank=True, null=True)),
                ('organic_results', models.TextField(blank=True, null=True)),
                ('pagination', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
