# Generated by Django 3.0.5 on 2020-12-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201223_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semrush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('seed_keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('keyword_difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('ccp', models.CharField(blank=True, max_length=50, null=True)),
                ('competitive_density', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_results', models.CharField(blank=True, max_length=50, null=True)),
                ('serp_Features', models.CharField(blank=True, max_length=50, null=True)),
                ('trend', models.CharField(blank=True, max_length=50, null=True)),
                ('click_potential', models.CharField(blank=True, max_length=50, null=True)),
                ('competitors', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
