# Generated by Django 3.1.3 on 2021-05-18 07:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_scrapjsondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storejsondata',
            name='source',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
