# Generated by Django 3.1.3 on 2021-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210518_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storejsondata',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
