# Generated by Django 3.0.5 on 2020-12-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_Img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
