# Generated by Django 3.1.3 on 2021-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210518_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storejsondata',
            name='source',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
