# Generated by Django 3.1.3 on 2021-05-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210519_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storejsondata',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
