# Generated by Django 3.0.5 on 2021-01-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semrush',
            old_name='group',
            new_name='tags',
        ),
    ]
