# Generated by Django 3.0.5 on 2021-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210104_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semrush',
            name='ccp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='click_potential',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='competitive_density',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='competitors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='keyword_difficulty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='number_of_results',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='seed_keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='serp_Features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='trend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semrush',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
