# Generated by Django 3.1.3 on 2021-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210519_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storejsondata',
            name='source',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
