# Generated by Django 3.0.5 on 2021-01-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210104_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semrush',
            name='volume',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
