# Generated by Django 3.0.5 on 2021-01-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_scrapweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapweb',
            name='title',
            field=models.TextField(),
        ),
    ]
