# Generated by Django 3.0.5 on 2021-01-19 07:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210118_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapGoogleDataLinkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Semrush')),
            ],
        ),
    ]
