# Generated by Django 3.0.5 on 2021-01-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_scrapgoogledatalinkdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapgoogledatalinkdata',
            name='keyword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UploadGoogleDataLink'),
        ),
    ]
