# Generated by Django 3.0.5 on 2021-01-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210119_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapgoogledatalinkdata',
            name='keyword_id',
            field=models.IntegerField(),
        ),
    ]
